services:
  backend:
    image: myusername/vinylo-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/sql_app.db
      - FRONTEND_URL=http://localhost:5173 # Change this in production
      - ALLOWED_ORIGINS=*
      - SPOTIFY_REDIRECT_URI=http://localhost:8000/api/callback/spotify # Change this in production

  frontend:
    image: myusername/vinylo-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
