services:
  backend:
    image: myusername/vinylo-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/sql_app.db
    command: sh -c "mkdir -p data && uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    image: myusername/vinylo-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
